/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'

const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesByTo {
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/translate'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/translate'
  id: '__root__' | '/api/translate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiTranslateRoute: typeof ApiTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiTranslateRoute: ApiTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
